### PR TITLE
Make customProperties work as expected

### PR DESCRIPTION
**Pull request by ragingdave**
I know you had said that this package will be left as is but I was hoping that wouldn't include PR's....

When using customProperties as it stands now, the expected results would be that the image shown would be the image with the customProperties only. That is not the case and although you can set the image and the customProperties are added, they aren't respected when looking up the image for detail or Form views.

This just handles that particular case so that customProperties are expected.

### CODE REVIEW

**Comment by jameslkingsley** [comment]
Could you resolve the merge conflict please, and then I'll merge it

**Comment by ragingdave** [comment]
Turns out there is a bug there, so hold off a merge for now.

**Comment by ragingdave** [comment]
@jameslkingsley it's close, I'm currently testing my updates in an actual app to try and uncover any bugs.

It turned out to be a larger change than I had originally thought, but it was due to how the array was being handled on the frontend for the ml_ properties as well as those overwriting other properties since the ml_ properties weren't field specific so having multiple image fields with custom properties caused every upload to have the last one defined.

I'll add another comment when it should be ready

**Comment by ragingdave** [comment]
Alright I did some testing, uploads/edits/etc. Everything seems to be looking ok. The only thing I didn't do was build the frontend assets with the removal of the ml_ items but that _should_ be fine.

**Comment by ragingdave** [comment]
@jameslkingsley if there's anything I can do to speed this along, please let me know

**Comment by gavnyx** [comment]
when this PR will merge to master? thank you

**Comment by ragingdave** [comment]
Is this package being maintained anymore? Currently using it in a soon to be production application and need to know if I should just fork it and move on...

**Comment by jameslkingsley** [comment]
Really sorry, haven't had time to look at this PR. Will come back to it when the project I'm currently working on circles back to Nova development. In the meantime I recommend using @ragingdave's fork instead of the main branch.

**Pull request merged**
